@API_HostAddress = http://localhost:5048
@Cute_Ducks = cute-ducks
@Other_Duck_Code = MWEny
@Google_Link = RHaeN
@secret = secret-duck

POST {{API_HostAddress}}/api/shortlinks
Content-Type: application/json
Accept: application/json

{
    "longurl": "https://hips.hearstapps.com/hmg-prod/images/four-ducklings-on-grass-royalty-free-image-1732103736.jpg?crop=0.8891xw:1xh;center,top&resize=1200:*"
}

###

GET {{API_HostAddress}}/api/shortlinks/QXHlA
Content-Type: application/json

###

POST {{API_HostAddress}}/api/shortlinks/verification
Content-Type: application/json

{
    "shortalias": "secret-duck",
    "password": "wrongpassword"
}

###

GET {{API_HostAddress}}/api/analytics/4vSAO?startDate=2005-01-01&endDate=2030-01-01
Content-Type: application/json