@API_HostAddress = http://localhost:5048
@Cute_Ducks = http://localhost:5048/api/shortlinks/cute-ducks

POST {{API_HostAddress}}/api/shortlinks
Content-Type: application/json
Accept: application/json

{
    "longurl": "https://google.com/"
}

###

GET {{API_HostAddress}}/api/shortlinks/RHaeN
Content-Type: application/json

###
