@API_HostAddress = http://localhost:5048
@noPassword_customAlias = cute-ducks
@secret_customAlias = secret-duck

@noPassword_shortCode = yioOr3
@secret_shortCode = URsGLW

@password = password

POST {{API_HostAddress}}/api/shortlinks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
    "longurl": "httpgoogle.com"
}

###

GET {{API_HostAddress}}//api/shortlinks/kqHiKT
Content-Type: application/json

###

GET {{API_HostAddress}}/api/shortlinks/{{noPassword_customAlias}}
Content-Type: application/json

###

GET {{API_HostAddress}}/api/shortlinks/{{noPassword_shortCode}}
Content-Type: application/json

###

GET {{API_HostAddress}}/api/shortlinks/{{secret_customAlias}}
Content-Type: application/json

###

GET {{API_HostAddress}}/api/shortlinks/{{secret_shortCode}}
Content-Type: application/json

###

POST {{API_HostAddress}}/api/shortlinks/verification
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "shortalias": "password-test",
  "password": "p"
}

###

POST {{API_HostAddress}}/api/shortlinks/verification
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "shortalias": "{{secret_customAlias}}",
    "password": "{{password}}"
}

###


POST {{API_HostAddress}}/api/shortlinks/verification
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "shortalias": "Gbe6Uc",
    "password": "{{password}}"
}

###

GET {{API_HostAddress}}/api/analytics/cute-ducks?startDate=2026-03-20&endDate=2026-03-28
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

GET {{API_HostAddress}}/api/analytics/visits?startDate=2026-03-27&endDate=2026-03-27
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
# @name create 
GET http://{{API_HostAddress}}/api/authentication
Content-Type: application/json
Accept: application/json

> {%
    client.global.set("auth_token", response.body.token)
%}